CREATE TABLE user(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rating INTEGER,
    fav_accepted INTEGER DEFAULT 0,
    fav_requested INTEGER DEFAULT 0,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    realname TEXT NOT NULL,
    phone TEXT NOT NULL,
);