CREATE TABLE "category"(
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "cat_name" TEXT
);

INSERT INTO "category" ("cat_name")
VALUES
    ('sports'),
    ('family'),
    ('kids'),
    ('volunteers needed'),
    ('pets'),
    ('emergency'),
    ('health'),
   ('food'),
  ('relationship'),
    ('advice'),
    ('travel'),
  ('wedding'),
    ('career'),
    ('needs fixing'),
    ('community'),
    ('education'),
    ('gaming'),
    ('IT'),
    ('plants'),
    ('creative'),
   ('misc'),
    ('religion & spirituality'),
    ('ridesharing')
;