CREATE TABLE favor(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    giver_id INTEGER REFERENCES user(id) ON DELETE CASCADE,
    reciever_id INTEGER REFERENCES user(id) ON DELETE CASCADE,
    redeemed BOOLEAN,
    expiration_date TIMESTAMP,
    public BOOLEAN,
    user_location TEXT,
    tags TEXT,
    category INTEGER REFERENCES category(id),
    rating  INTEGER,
    posted  TIMESTAMP,
);