CREATE TABLE "outstanding" (
    "id" integer PRIMARY KEY GENERATED BY
        DEFAULT AS IDENTITY,
        "favor_id" integer REFERENCES "favor" (id) ON DELETE CASCADE,
        "users_id" integer REFERENCES "user" (id) ON DELETE CASCADE,
        "receiver_id" integer REFERENCES "user" (id) ON DELETE CASCADE,
        "receiver_redeemed" boolean,
        "giver_redeemed" boolean
);

