CREATE TABLE "outstanding"(
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "favor_id" INTEGER REFERENCES "favor"(id) ON DELETE CASCADE,
    "users_id" INTEGER REFERENCES "user"(id) ON DELETE CASCADE,
    "reciever_id" INTEGER REFERENCES "user"(id) ON DELETE CASCADE,
    "reciever_redeemed" BOOLEAN,
    "giver_redeemed" BOOLEAN
);